### ISSUE TITLE
 The requested module 'firebase/app' is expected to be of type CommonJS, which does not support named exports

### ISSUE THREAD

**Issue by nielsvandermolen** [jthegedus/svelte-adapter-firebase#47]
**Describe the bug**
I decided to use [v9](https://firebase.google.com/docs/reference/js/v9) of the Firebase API.

The biggest change to v8 is that you no longer need to load all the Firebase JS but just the functions that you are going to use.

Instead of 
```
import firebase from "firebase/app"
````
it is called by

```
import { initializeApp } from 'firebase/app';
````

In development this works fine however when running the build with the Svelte adapter I get the following error:

````
> Using svelte-adapter-firebase
> The requested module 'firebase/app' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'firebase/app';
const {getApp, initializeApp} = pkg;
file:///var/www/svelte/.svelte-kit/output/server/app.js:6
import {getApp, initializeApp} from "firebase/app";
````

**To Reproduce**
1. Initiate an App with v9 logic
2. Run a build with svelte adapter 0.6.3

**Expected behavior**
Being able to build without having to add something like `import firebase from "firebase/app"`

**Additional context**
I do not know where this error is triggered but it seems related to the adapter. The initial svelte build does seem to work. With the support of ESMBuild in https://github.com/jthegedus/svelte-adapter-firebase/pull/39  you would expect that it should work but maybe there is a hardcoded check on firebase/app that it is CommonJS somewhere?

**Comment by nielsvandermolen** [comment]
Might be related to this similar issue in another adapter https://github.com/sveltejs/kit/issues/1379

**Comment by babichjacob** [comment]
This isn't a bug with this adapter, by the way, because it'll happen with any. I'd also suggest upgrading to Node 14.16.1 if not 16.1.0 to solve this (because I've seen that be the reason for issues with a similar error message).

**Comment by nielsvandermolen** [comment]
Thanks! Confirmed that updating to Node 14.16.1 solved this issue.

**Comment by jthegedus** [comment]
Cloud Functions latest Node.js support is `14.x.x` so I highly recommend using that. I don't think there is a way for me to enforce this with the adapter unfortunately.

**Comment by sebmade** [comment]
problem persists
if I import firebase/firestore I have the same problem
if I upgrade to node v16.5.0, the problem is now on firebase/auth !!!
is there a problem from firebase v9 packaging ?

**Comment by sebmade** [comment]
finally it works by doing "npm i firebase@9.0.0-beta.6" under functions directory

**Comment by jthegedus** [comment]
@sebmade You shouldn't need to or be expected to add `firebase` client SDK to the Functions directory. Are you able to provide more information on your setup, how and where you're using the SDK in your app so we can better understand the exact scenario. Depending on the use case I feel the resolution is not strictly correct and do not want to lead others astray.

**Comment by sebmade** [comment]
@jthegedus my config is a just new installation of a svelte-kit app by using npm init svelte@next my-app, so I use @sveltejs/kit 1.0.0-next.127. I've import firebase-admin@9.10.0 for server side calls and firebase@9.0.0-beta.6 for client side calls. I use svelte-adapter-firebase@0.9.2 and svelte@3.34.0.
I've imported firebase-admin also in functions directory because I have a specific google function that used it.
I think there is a conflict declaration between firebase-admin and firebase.

**Comment by sebmade** [comment]
Finally it reproduce again, you're true : install firebase in functions dir don't work
I don't understand how it happens to work once time
Now I try to manage putting firebase and firebase-admin in dependencies vs devDependencies in root packages.json
In devDependencies I have the commonJS error describe above in dependencies I have "IDBIndex is not defined" error
I remove my node_modules dir and "npm i" but nothing changed

Don't understand what happens, I'm open to ideas :)

**Comment by jthegedus** [comment]
>IDBIndex is not defined

This error occurs because the Firebase (client) SDK relies on IDBIndex which is only available in Web environment, not server.

Server libs:

```
firebase-admin
firebase-functions
```

Client (web) libs:

```
firebase
```

SvelteKit is an SSR framework, so understanding which parts of SvelteKit will execute on the server is crucial. Be careful where you use `firebase` in SvelteKit because sometimes it will try and run during the SSR context.

The adapter works by compiling your SvelteKit SSR dependencies so you shouldn't need to modify your `functions/package.json` dependencies to support the SvelteKit code that executes on the Cloud Function. All code that SvelteKit needs for Cloud Function will be built when the SvelteKit build happens.

With that cleared up. Here is the breakdown across SvelteKit rendering scenarios:

SSR libs:

```
firebase-admin
```

Web libs:

```
firebase
```

In your SvelteKit app if you want to use Firebase in SSR you need to use `firebase-admin` only in the SSR parts of SvelteKit. Similarly, if you want to use Firebase on client side (web) you need to use `firebase` but only in non-SSR parts of SvelteKit.

SvelteKit is less clear than other libs (like Next.js) on what executes where, which makes the usage more difficult. But the `IDBIndex` error is the `firebase` lib trying to execute in a SvelteKit SSR context, and changing Cloud Function `function/package.json` dependencies won't do anything.

`firebase` - needs to be used when in `browser`, and `onMount`:

```js
import { browser } from '$app/env';
import { onMount } from 'svelte';

onMount(async () => {
	if (browser) {
		// it is safe to import firebase client sdk
	}
});
```

`firebase-admin` - needs to execute in a server environment, since our SSR runs in Cloud Functions that fits:

`<script context="module">` & `<script>` blocks are sometimes SSR, sometimes CSR. You could guard the `import` using `!browser` as suggested for client. An easier way is to just use `firebase-admin` in SvelteKit Endpoints, which always execute in SSR. So any `*.json.js` file in `routes` it is safe to use `firebase-admin`.

Recap:

- `firebase-admin`: use in SvelteKit Endpoints.
- `firebase`: `onMount` & `browser` then you can safely `import`.

**Comment by sebmade** [comment]
thanks @jthegedus for this clear explanation
it works now 👍 
in fact I forgot "if (browser)" in an onMount() function, I was thinking it was only call on client side, but it's not, it's also use server side on prerendering : where the previous problem happened

IDBIndex error still there if I put firebase in dependencies rather than devDependencies, I had the same problem with sapper
using only devDependencies let it works

**Comment by jthegedus** [comment]
>IDBIndex error still there if I put firebase in dependencies rather than devDependencies, I had the same problem with sapper using only devDependencies let it works

I've not had this issue. I have `firebase` in `dependencies` & `firebase-admin` in `devDependencies` (because it gets compiled into the SSR on build)
